services:
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - shared-gateway
      - fastchat
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
networks:
  fastchat:
    external: true
  shared-gateway:
    external: true